weather_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: airflow
      password: 'airflow1234@#'
      dbname: weather_dwh   # database name
      schema: reporting        # schema name
      threads: 1
      keepalives_idle: 0